### PR TITLE
Update VisualBuilder to Allow External Bundling

### PR DESCRIPTION
**Pull request by darthtrevino**
It is common for our use-cases to use a Javascript bundler (e.g. Webpack, Browserify, jspm) to load third-party scripts and assets. The current mechanism of an "externalJS" array leaves a lot to be wanted: it demands that developers load scripts and their dependencies in the correct order, and that those dependencies don't have a module-loading mechanism or embedded assets. It also precludes the possibility of a rich asset pipeline that performs linting, transpilation, and embeds styles and data.

This commit allows developers to specify bundle configurations in `pbiviz.json`, which allow them to sidestep the pbiviz script-building mechanism while retaining the ability to use the `pbiviz` tool for live-reloading and packaging.

Using this change, here's the configuration I'm using to perform a custom build
`pbiviz.json`
```json
{
  "visual": {
    "name": "pvtest",
    "displayName": "pvtest",
    "guid": "PBI_CV_34C79648_8924_4ACD_BE2B_F90F209A8CBA",
    "visualClassName": "Visual",
    "version": "1.0.0",
    "description": "",
    "supportUrl": "",
    "gitHubUrl": ""
  },
  "bundle": {
    "js": {
      "path": ".tmp/drop/visual.bundle.js"
    }
  },
  "apiVersion": "1.1.0",
  "author": {
    "name": "",
    "email": ""
  },
  "assets": {
    "icon": "assets/icon.png"
  },
  "externalJS": [
  ],
  "style": "style/visual.less",
  "capabilities": "capabilities.json"
}
```

`webpack.config.js`: 

```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: path.join(__dirname, '.tmp', 'build', 'transpiled', 'visual.js'),
    output: {
        path: path.join(__dirname, '.tmp', 'drop'),
        filename: 'visual.bundle.js'
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: 'style!css' },
            { test: /\.(js|jsx)$/, loaders: [ 'imports?powerbi=>window["powerbi"]' ] }
        ]
    },
    plugins: [
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.DefinePlugin({
          'process.env': {
              'NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
          }
      })
    ]
};
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "allowJs": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "ES5",
    "sourceMap": false,
    "out": "./.tmp/build/transpiled/visual.js"
  },
  "files": [
    ".api/v1.1.0/PowerBI-visuals.d.ts",
    "typings/index.d.ts",
    "./src/visual.ts"
  ]
}

```

`package.json`
```json
{
  "name": "visual",
  "devDependencies": {
    "imports-loader": "^0.6.5",
    "onchange": "^2.5.0",
    "typescript": "^1.8.10",
    "typings": "^1.3.2",
    "webpack": "^1.13.1"
  },
  "dependencies": {
    "debug": "^2.2.0"
  },
  "scripts": {
    "tsc": "tsc",
    "webpack": "webpack",
    "watch:tsc": "npm run tsc -- -w",
    "watch:webpack": "npm run webpack -- -w",
    "watch:copy": "onchange '.tmp/drop/visual.bundle.js' -- npm run copy",
    "watch": "npm-run-all -p watch:*",
    "copy": "cp .tmp/drop/visual.bundle.js .tmp/drop/visual.js",
    "start:pbiviz": "pbiviz start",
    "start": "npm-run-all tsc webpack copy -p watch start:pbiviz"
  }
}
```

`src/visual.ts`
```
const log = require("debug")("Visual");

module powerbi.extensibility.visual.PBI_CV_34C79648_8924_4ACD_BE2B_F90F209A8CBA.PBI_CV_34C79648_8924_4ACD_BE2B_F90F209A8CBA  {
    log("Loading Visual");
    export class Visual implements IVisual {
        private target: HTMLElement;
        private updateCount: number;

        constructor(options: VisualConstructorOptions) {
            log("Visual constructor", options);
            this.target = options.element;
            this.updateCount = 0;
        }

        public update(options: VisualUpdateOptions) {
            log("Visual update", options);
            this.target.innerHTML = `<p>Update count: <em>${(this.updateCount++)}</em></p>`;
        }

        public destroy(): void {
            // TODO: Perform any cleanup tasks here
        }
    }

    export var PBI_CV_34C79648_8924_4ACD_BE2B_F90F209A8CBA = {
        name: 'PBI_CV_34C79648_8924_4ACD_BE2B_F90F209A8CBA',
        displayName: 'pvtest',
        class: 'Visual',
        version: '1.0.0',
        apiVersion: '1.1.0',
        create: (options) => new powerbi.extensibility.visual.PBI_CV_34C79648_8924_4ACD_BE2B_F90F209A8CBA.Visual(options),
        custom: true
    };
}
```

### CODE REVIEW

**Comment by darthtrevino** [comment]
I'm going to commit a template to automate some of this boilerplate

**Comment by spatney** [comment]
Just as a note the externalJS attribute only exists because typescript has a bug in versions prior to 2.0 that doesn't compile some javascript libraries (ex. pixijs) defined in tsconfig properly. This was to serve as a workaround.

Agreed that it might be useful to have a notion of different types of "builders", though I don't like the idea of this being controlled via a config, and it makes future updates to the tool more complicated and difficult to test.

A better change would be to decouple the builder entirely, and allow for developers to specify which one they would like to use by importing the right module. Having said that, the thing to keep in mind is that we perform some changes "pre-compile" to ts/less files to encapsulate the code. You seem to have gotten around that by manually specifying the plugin in the ts config, which is incorrect as the plugin is an internal concept and we want to have full control on its generation since it provides critical information on what version of adapters to load and how to create visuals.

I would suggest if you still want to use webpack (or others) to build/bundle your code, you can, but just have it all bundle into one JS file and include that into your TS config and keep only the visual shell in the TS file.

**Comment by darthtrevino** [comment]
Your concerns sound reasonable. The approach you're describing is problematic though. Bundlers will crawl a dependency graph using require or import statements starting from an entry point script. This entry point is usually the point at which you mount your application into the DOM. In the setup you described, we want to access functions that have been made available within the bundle and use them in the Typescript bootstrapping script to initialize the app. 

To pull this off in webpack, we need to use either the `expose-loader` or the `script-loader` to define functions that the visual can use to begin rendering. These loaders are executed in the global context (window object), which means these bootstrapping functions that Typescript would use are window globals. This is just as, if not more dangerous than having the visual GUID embedded in your code.

I'll research this a bit more to see if there's a way around that, but the ideal scenario would be webpacking the visual starting at the root. This may be an appropriate case for a custom webpack plugin that could inject the GUID-modified namespaces into the bootstrapping sequence.

**Comment by darthtrevino** [comment]
I played around with making a Webpack plugin last night, and it looks promising. The bundling configuration would look like this:

```
const path = require('path');
const webpack = require('webpack');
const PowerBIVisualPlugin = require('./PowerBIVisualPlugin');

module.exports = {
    entry: path.join(__dirname, 'src/visual.ts'),
    output: {
        path: path.join(__dirname, '.tmp', 'webpack'),
        filename: 'visual.bundle.js'
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: 'style!css' },
            { test: /\.(ts|tsx)$/, loaders: [ 'ts', 'imports?powerbi=>window["powerbi"]' ] }
        ]
    },
    plugins: [
      new PowerBIVisualPlugin(require('./pbiviz.json')
    ]
};
```

PowerBI Visual Plugin: This is a sketch implementation that uses sentinel comments, which won't work in transpiled TS because it strips the closing comment. However, you can tap into the AST emitter in the plugin and use that to inject the guid-ified namespace without requiring sentinel comments.
 
```
const pbiviz = require('./pbiviz.json');

const VISUAL_START = "// powerbi-begin-visual";
const VISUAL_END = "// powerbi-begin-visual";
const guidNsHeader = guid => `
  var ${guid};
  (function (${guid}) {
`;
const guidNsFooter = guid => `
${guid}.Visual = Visual;
})(${guid} = visual.${guid} || (visual.${guid} = {}));
`;

function PowerBIVisualPlugin(options) {this.options = options;}

function wrapEntry(entry, guid) {
  return `
    ${entry.replace(VISUAL_START, guidNsHeader(guid)).replace(VISUAL_END, guidNsFooter(guid))}
    (function (powerbi) {
   	    var visuals;
   	    (function (visuals) {
   	        var plugins;
   	        (function (plugins) {
   	            plugins.${guid} = {
   	                name: '${guid}',
   	                displayName: ...
   	                create: function (options) { return new powerbi.extensibility.visual.${guid}.Visual(options); },
   	                custom: true
   	            };
   	        })(plugins = visuals.plugins || (visuals.plugins = {}));
   	    })(visuals = powerbi.visuals || (powerbi.visuals = {}));
   	})(powerbi || (powerbi = {}));
  `;
}

PowerBIVisualPlugin.prototype.apply = function(compiler) {
  compiler.plugin('compilation', function(compilation, callback) {
    compilation.plugin('seal', function() {
      const entry = compilation.modules[0];
      entry._source._value = wrapEntry(entry._source._value, this.options.visual.guid);
    });
  });
};

module.exports = PowerBIVisualPlugin;
```

**Pull request closed without merging**
